### ISSUE TITLE
Providers causing module error

### ISSUE THREAD

**Issue by lukemcfarlane** [noeticpenguin/ngForce#20]
I seem to get a module error when including any of the following javascript files:
lib/ngforce/ngforce-sfTemplate.js
lib/ngforce/ngforce-remoteObjects.js
lib/ngforce/ngforce-visualForceRemoting.js

It is interesting to note that these three files are providers, whereas the other ones are factories.

The error I am getting is:
Uncaught Error: [$injector:modulerr] http://errors.angularjs.org/1.2.16/$injector/modulerr?p0=leave.requests&p1=…angularjs.org%2F1.2.16%2F%24injector%2Fmodulerr%3Fp0%3DngForce%26p1%3DErro...<omitted>...4)

When I just include build/ngForceWithRequirements.min.js I get the same error message. 

When I include all files EXCLUDING the three mentioned above, everything works and runs without a hitch.

Thanks in advance!

**Comment by arindambiswas** [comment]
@venorm Faced the same issue till I read the docs again and understood that ngforce.config needs to be injected. Its a part of the deploy bundle.
