### ISSUE TITLE
If an exception is thrown during a vfr.send() call, no useful information comes out of the promise, nor is it rejected

### ISSUE THREAD

**Issue by Oblongmana** [noeticpenguin/ngForce#34]
**(I should have a PR in for this issue shortly, including a fix for #32 as well)**

When an exception is thrown during a vfr.send() call:
 1) The promise resolves, when rejecting would be the logical action
 2) No information on the exception is returned from the promise

Cause
===
 When an exception occurs, `result` is `null`, so the `handleResultWithPromise(...)` method goes down the `} else if (typeof nullok !== 'undefined' && nullok) {` branch. 

However, this branch is only meant for handling the situation where the remote action actually _returns_ null, not the situation where `result` is `null` due to an exception happening

Solution
===
Add an extra branch that checks for `event.status === false`, as per https://www.salesforce.com/docs/developer/pages/Content/pages_js_remoting.htm. This will then do `deferred.reject(...)`, returning the `event.message`, `event.where`, and `event.method`, plus an `errorCode` (as happens with the nullOK reject branch).

**Comment by noeticpenguin** [comment]
wow, I totally missed this. Please disregard my comments about nullok on the pr. Accepting it asap.
